project:
  type: website

website:
  title: "Aaron's Blog"
  search: false
  navbar:
    background: "#fff"
    collapse: false 
    left:
      - href: index.qmd
        icon: house-door-fill
        text: " "

format:
  html:
    theme: 
      - cosmo
      - theme.scss
    css: styles.scss

execute:
  freeze: auto



